services:
  - type: web
    name: campus-career-backend
    runtime: node
    rootDir: backend/server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 1d
      - key: JWT_REMEMBER_EXPIRE
        value: 30d
      - key: TPO_REGISTRATION_SECRET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: COOKIE_SAMESITE
        value: none
      - key: COOKIE_SECURE
        value: true
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
